
name: freecad
version: 0.19
summary: development version
description: development version This version is far from being bug free but integrates the latest FreeCAD technologies
parts:
 example-part:
    plugin: copy
    files:
      bin/launcher : bin/launcher
      fontconfig/fonts.conf : fontconfig/fonts.conf
      etc/matplotlibrc : etc/matplotlibrc
    stage-packages:
      - git
      - git-core
      - netgen
      - vtk
      - occt
      - med
      - liblapack3
      - freecad
      - doxygen
      - libblas3
      - libboost1.67-dev
      - libboost-filesystem1.67-dev
      - libboost-program-options1.67-dev
      - libboost-python1.67-dev
      - libboost-regex1.67-dev
      - libboost-signals1.67-dev
      - libboost-system1.67-dev
      - libboost-thread1.67-dev
      - libcoin80c
      - libcoin-dev
      - libqt5webkit5-dev
      - libqt5svg5-dev
      - libqt5xmlpatterns5-dev
      - libqt5widgets5
      - libqt5quickwidgets5
      - libqt5multimediawidgets5
      - libtcl8.6
      - libtk8.6
      - libsz2
      - libwind0-heimdal
      - libpyside2-dev
      - libshiboken2-dev
      - libsasl2-2
      - librtmp1
      - libroken18-heimdal
      - libpython3.8
      - libpython3.8-minimal
      - libldap-2.4-2
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libheimntlm0-heimdal
      - libheimbase1-heimdal
      - libhcrypto4-heimdal
      - libgssapi3-heimdal
      - libcurl3-gnutls
      - libcurl4
      - libasn1-8-heimdal
      - libaec0
      - libhdf5-103
      - libxerces-c3.2
      - libfreetype6-dev
      - libxt-dev
      - libxmu-dev
      - libxi-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libfreeimage-dev
      - libtbb-dev
      - python3-numpy
      - python3-matplotlib
      - python3-six
      - python3-pyparsing
      - python3-setuptools-scm
      - python3-cycler
      - python3-dateutil
      - python3-git
      - python3-ply
      - python3-pip
      - python3-pivy
      - graphviz
      - calculix-ccx
      - libc-bin
      - locales
      - debconf
      - ttf-bitstream-vera
      - xfonts-base
      - xfonts-encodings
      - xfonts-utils
      - xfonts-scalable
      - fonts-dejavu-core
    override-stage: |
      snapcraftctl stage
      sed -i -E \
        "s|^Icon=(.*)|Icon=\${SNAP}/opt/local/FreeCAD-0.19/share/icons/hicolor/scalable/apps/org.freecadweb.FreeCAD.svg|g" \
        opt/local/FreeCAD-0.19/share/applications/org.freecadweb.FreeCAD.desktop
    prime:
      - bin
      - etc
      - fontconfig
      - opt
      - lib
      - usr/lib
      - usr/libx86_64-linux-gnu/
      - usr/bin
      - usr/share
      - -opt/local/FreeCAD-0.19/share/docs
      - -opt/local/FreeCAD-0.19/share/doc
      - -opt/local/FreeCAD-0.19/include

apps:
 freecad:
  common-id: org.freecadweb.FreeCAD.desktop
  desktop: opt/local/FreeCAD-0.19/share/applications/org.freecadweb.FreeCAD.desktop
  command: bin/launcher
  plugs: [ locale-control,x11,opengl,network-bind,home,unity7 ]
  environment:
      GIT_TEMPLATE_DIR: $SNAP/usr/share/git-core/templates
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core
